# Generated by Django 4.1.2 on 2022-10-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_internalclient_order_delete_externalclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TashqiMijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=50)),
                ('passport_seria', models.CharField(max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.externalblog')),
            ],
        ),
        migrations.CreateModel(
            name='IchkiMijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=50)),
                ('passport_seria', models.CharField(max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.internalblog')),
            ],
        ),
    ]
