# Generated by Django 4.1.2 on 2022-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ichkimijoz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ichkimijoz',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='tashqimijoz',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tashqimijoz',
            name='surname',
        ),
        migrations.AddField(
            model_name='ichkimijoz',
            name='fullname',
            field=models.CharField(default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tashqimijoz',
            name='fullname',
            field=models.CharField(default='null', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tashqimijoz',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
