# Generated by Django 4.1.2 on 2022-10-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ichkimijoz',
            options={'verbose_name': 'IchkiMijoz', 'verbose_name_plural': 'IchkiMijozs'},
        ),
        migrations.AlterModelOptions(
            name='tashqimijoz',
            options={'verbose_name': 'TashqiMijoz', 'verbose_name_plural': 'TashqiMijozs'},
        ),
        migrations.AlterField(
            model_name='ichkimijoz',
            name='passport_seria',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='ichkimijoz',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
