# Generated by Django 4.1.2 on 2024-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_ichkimijoz_name_remove_ichkimijoz_surname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ichkimijoz',
            options={'verbose_name': 'IchkiMijoz', 'verbose_name_plural': 'IchkiMijozlar'},
        ),
        migrations.AlterModelOptions(
            name='tashqimijoz',
            options={'verbose_name': 'TashqiMijoz', 'verbose_name_plural': 'TashqiMijozlar'},
        ),
    ]
