# Generated by Django 4.1.2 on 2022-10-30 02:39

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to=main.models.slugify_upload)),
                ('img2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('img3', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
        migrations.CreateModel(
            name='ExternalBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img1', models.ImageField(upload_to=main.models.slugify_upload)),
                ('img2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('img3', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InternalBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to=main.models.slugify_upload)),
                ('img2', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('img3', models.ImageField(blank=True, upload_to=main.models.slugify_upload)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=120)),
                ('img', models.ImageField(upload_to=main.models.slugify_upload)),
                ('the_task', models.CharField(max_length=100)),
                ('Rating', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'WorkerContact',
                'verbose_name_plural': 'WorkerContacts',
            },
        ),
        migrations.CreateModel(
            name='InternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=50)),
                ('passport_seria', models.CharField(max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.internalblog')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=50)),
                ('passport_seria', models.CharField(max_length=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.externalblog')),
            ],
        ),
    ]
