# Generated by Django 4.1.2 on 2022-11-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_internalclient_order_delete_externalclient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalblog',
            old_name='img1',
            new_name='img',
        ),
    ]
