# Generated by Django 4.1.2 on 2023-10-05 23:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_img1_externalblog_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='description',
        ),
        migrations.AlterField(
            model_name='externalblog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='internalblog',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='internalblog',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
