# Generated by Django 4.1.2 on 2024-05-11 19:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_announcement_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.CharField(default='sssss', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='externalblog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='internalblog',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='internalblog',
            name='title',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
