# Generated by Django 4.1.2 on 2024-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalblog',
            name='title',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
